Admin_index:
    path:     /
    defaults: { _controller: "AdminBundle:Default:index" }
    
Admin_register:
    path:     /register
    defaults: { _controller: "AdminBundle:User:register" }
    
Admin_video_board:
    path:     /videoboard/{id}
    defaults: { _controller: "AdminBundle:Video:videoBoard" }
    
Admin_musique_board:
    path:     /musiqueboard/{id}
    defaults: { _controller: "AdminBundle:Musique:musiqueBoard" }

Admin_suppr_image:
    path:   /image/remove/{id}
    defaults: { _controller: "AdminBundle:Video:deleteImage" }
    
Admin_suppr_extrait:
    path:   /extrait/remove/{id}
    defaults: { _controller: "AdminBundle:Video:deleteExtrait" }
    
Admin_suppr_liaisonMusique:
    path:   /liaisonmusique/remove/{id}
    defaults: { _controller: "AdminBundle:Video:deleteLiaisonMusique" }
    
Admin_suppr_video:
    path:   /video/remove/{id}
    defaults: { _controller: "AdminBundle:Video:deleteVideo" }
    
Admin_suppr_musique:
    path:   /musique/remove/{id}
    defaults: { _controller: "AdminBundle:Musique:deleteMusique" }