<?php

namespace Symfony\Bundle\AsseticBundle\Repository;

/**
 * ExtraitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraitRepository extends \Doctrine\ORM\EntityRepository
{
}
