# sources:
#     resource: "@SourcesBundle/Controller/"
#     type:     annotation
#     prefix:   /

sources:
    resource: "@SourcesBundle/Resources/config/routing.yml"


# app:
#     resource: '@AppBundle/Controller/'
#     type: annotation
